### ISSUE TITLE
Example google collab cell has a error when running

### ISSUE THREAD

**Issue by kleenkanteen** [truera/trulens#707]
In the TruLens quickstart here: https://www.trulens.org/trulens_eval/quickstart/

For the collab:

![image](https://github.com/truera/trulens/assets/67878058/1199ebf7-e6fc-4eb4-8567-564b54a70a21)

I uncommented and ran the first line: 
![image](https://github.com/truera/trulens/assets/67878058/ea2f538b-bfbf-4cd3-bf13-af640e57b602)

Ran all the cells until this cell, and then got this error:

![image](https://github.com/truera/trulens/assets/67878058/559d1c3e-81cc-4724-95e3-f884fe20fa93)

The solution is to add llama_index to the very first cell: 
![image](https://github.com/truera/trulens/assets/67878058/0d556f3d-aa80-451b-b28d-3ef1fbeac303)

Now the cell runs fine:
![image](https://github.com/truera/trulens/assets/67878058/9479ee03-0906-463f-bdca-f6853b8fe174)

**Comment by joshreini1** [comment]
We should not require llama-index to import trulens here. Will take a look at the dependencies.

**Comment by joshreini1** [comment]
Added PR #714 that should fix this.

**Comment by thisiskeithkwan** [comment]
> Added PR #714 that should fix this.

Same problem different
Today on the latest version of trulens_eval

<img width="860" alt="image" src="https://github.com/truera/trulens/assets/26019476/c69788eb-34b6-480c-9c66-56fc17bd6f3f">

**Comment by ingridstevens** [comment]
This is still a problem. The fix I'm using is: 
`pip install llama-index==0.9.21`

**Comment by joshreini1** [comment]
Same issue as https://github.com/truera/trulens/issues/731

**Comment by joshreini1** [comment]
Please upgrade your trulens version if you are still experiencing this issue. Thanks!

**Comment by joshreini1** [comment]
Let me create a new issue for this litellm requirement. Will tag you
